[package]
name = "cli"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow.workspace = true
clap = { version = "4.5.50", features = ["derive"] }
crossbeam-channel = "0.5.15"
reqwest = { version = "0.12.24", features = ["stream"] }
shared = { path = "../shared" }
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
