[package]
name = "shared"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[lib]
crate-type = ["cdylib", "lib", "staticlib"]

[dependencies]
chrono = { version = "0.4.42", features = ["serde"] }
crux_core = { workspace = true }
crux_http = { workspace = true }
crux_kv = { workspace = true }
crux_platform = { workspace = true }
crux_time = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.145"
uniffi = "=0.29.4"
wasm-bindgen = "0.2.105"

[build-dependencies]
uniffi = { version = "=0.29.4", features = ["build"] }

[target.uniffi-bindgen.dependencies]
uniffi = { version = "=0.29.4", features = ["cli"] }

[features]
typegen = ["crux_core/typegen"]
