[package]
name = "shared"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3


[lib]
crate-type = ["lib", "staticlib", "cdylib"]
name = "shared"

[features]
typegen = ["crux_core/typegen"]

[dependencies]
crux_core.workspace = true
crux_http.workspace = true
crux_kv.workspace = true
serde = { workspace = true, features = ["derive"] }
uniffi = "=0.29.4"
wasm-bindgen = "0.2.105"
serde_json = "1.0"
derive_builder = "0.20.2"

[dev-dependencies]
insta = { version = "1.43.2", features = ["yaml"] }
serde_json = "1.0"

[target.uniffi-bindgen.dependencies]
uniffi = { version = "=0.29.4", features = ["cli"] }

[build-dependencies]
uniffi = { version = "=0.29.4", features = ["build"] }
