[package]
name = "crux_cli"
version = "0.1.1"
description = "Command line tool for crux_core"
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[[bin]]
name = "crux"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
ascent = "0.8.0"
camino = "1.1.11"
cargo_metadata = "=0.19"
clap = { version = "4.5.45", features = ["derive", "env"] }
convert_case = "0.8.0"
env_logger = "0.11.8"
guppy = "0.17.20"
iter_tools = "0.37.0"
lazy-regex = "3.4.1"
log = "0.4.27"
rustdoc-types = "=0.35.0"
serde = { workspace = true, features = ["derive"] }
serde-generate = "0.32.0"
serde-reflection = "0.5.0"
serde_json = "1.0.143"
thiserror.workspace = true
uniffi_bindgen.workspace = true

[dev-dependencies]
insta = { version = "1.43.1" }
pretty_assertions = "1.4.1"
rstest = "0.26.1"
