[package]
name = "shared"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[lib]
crate-type = ["cdylib", "lib", "staticlib"]

[[bin]]
name = "codegen"
required-features = ["cli"]

[dependencies]
async-sse = "5.1.0"
chrono = { version = "0.4.42", features = ["serde"] }
crux_core.workspace = true
crux_http.workspace = true
facet = { version = "0.30.0", features = ["chrono", "time"] }
futures = "0.3.31"
log = { version = "0.4.28", optional = true }
pretty_env_logger = { version = "0.5.0", optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.145"
url = "2.5.7"

[dev-dependencies]
insta = { version = "1.43.2", features = ["yaml"] }

# not wasm
[target.'cfg(not(target_family = "wasm"))'.dependencies]
rand = { version = "0.9.2", features = ["os_rng"] }
uniffi = "=0.29.4"

# wasm32-unknown-unknown, but not wasm32-wasip2
[target.'cfg(any(target_family = "wasm", not(all(target_os = "wasi", target_env = "p2"))))'.dependencies]
getrandom = { version = "0.3.4", features = ["wasm_js"] }
wasm-bindgen = "0.2.105"
js-sys = "0.3.82"

# wasm32-wasip2
[target.'cfg(all(target_os = "wasi", target_env = "p2"))'.dependencies]
crux_core = { workspace = true, features = ["facet_typegen"] }
crux_http = { workspace = true, features = ["facet_typegen"] }
wit-bindgen = "0.47.0"

[features]
cli = ["crux_core/cli", "dep:log", "dep:pretty_env_logger"]
facet_typegen = ["crux_core/facet_typegen"]
