[package]
name = "web-dioxus"
version = "0.1.0"
authors = ["Stuart Harris <stuart.harris@red-badger.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow.workspace = true
console_error_panic_hook = "0.1.7"
dioxus = { version = "0.6.3", features = ["web"] }
dioxus-logger = "0.6.2"
futures-util = "0.3.31"
gloo-net = "0.6.0"
js-sys = "0.3.82"
shared = { path = "../shared" }
tracing = "0.1.41"
wasm-bindgen = "0.2.105"
wasm-bindgen-futures = "0.4.55"
wasm-streams = "0.4.2"
