[package]
name = "web-leptos"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
futures-util = "0.3.31"
gloo-net = { version = "0.6.0", features = ["http"] }
js-sys = "0.3.82"
log = "0.4.28"
shared = { path = "../shared" }
wasm-bindgen = "0.2.105"
wasm-streams = "0.4.2"

# 0.8.* needs resolver>=2 which is not good for shared/uniffi-bindgen
# (see counter-next example for example of how to use the latest leptos version)
leptos = { version = "=0.7.8", features = ["csr"] }

[lints.clippy]
empty_docs = "allow"
