[package]
name = "web-leptos"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
log = "0.4.28"
shared = { path = "../shared" }

# 0.8.* needs resolver>=2 which is not good for shared/uniffi-bindgen
# (see counter-next example for example of how to use the latest leptos version)
leptos = { version = "=0.7.8", features = ["csr"] }

[lints.clippy]
empty_docs = "allow"
