[package]
name = "shared"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
rust-version.workspace = true

[features]
typegen = ["crux_core/typegen"]

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
automerge = { version = "=0.4.1", features = ["wasm"] }
crux_core.workspace = true
crux_kv.workspace = true
crux_time.workspace = true
futures = "0.3"
serde = { workspace = true, features = ["derive"] }
uniffi = "=0.29.4"
wasm-bindgen = "0.2"

[target.uniffi-bindgen.dependencies]
uniffi = { version = "=0.29.4", features = ["cli"] }

[build-dependencies]
uniffi = { version = "=0.29.4", features = ["build"] }
